### ISSUE TITLE
Cannot run example - SystemExit called on sdk = CueSdk()

### ISSUE THREAD

**Issue by mik1893** [CorsairOfficial/cue-sdk-python#1]
Hi,
Thanks for the Python support really glad you guys are doing it.
Just trying to run the sample script but I keep getting a SystemExit called inside CueSDK()

![image](https://user-images.githubusercontent.com/1483174/77518876-6cdf6f00-6e76-11ea-80a0-3747d0d6eca6.png)

Is there anything I'm missing? I have installed VS Redistributable - using Python 3.8.2

**Comment by mik1893** [comment]
found out you have to still copy the DLL files - the dll folder needs to be added in the directory where your python script runs

**Comment by intrueder** [comment]
@mik1893 package is still in beta, but actually DLL files should be automatically copied under `site-packages`. Something is wrong. I'll take a look into it.
Btw, you can override path to DLL by passing an argument to `CueSdk(sdk_path)`

**Comment by intrueder** [comment]
Hey @mik1893 
A new version v0.2.5 was released today. Hope it works!
Thanks for reporting this!
