### ISSUE TITLE
Issue with set_led_colors_buffer_by_device_index function

### ISSUE THREAD

**Issue by stevenj2019** [CorsairOfficial/cue-sdk-python#13]
Hey Guys, 

I have to be honest I think 0i am somehow being dumb and missing something obvious but I cant see the issue and the traceback seems to come from api.py

`
          from cuesdk import CueSdk
          
          SDK = CueSdk()
          SDK.connect()
          Device_Count = SDK.get_device_count()
          LED_Devices = dict()
          for Device in range(Device_Count):
              
              LED_Devices[Device] = SDK.get_led_positions_by_device_index(Device)
          
              for LED in LED_Devices.keys():
                  LED_Devices[Device][LED] = (255,255,255)
          
                  print(type(Device))
                  print(type(LED_Devices[Device]))
                  SDK.set_led_colors_buffer_by_device_index(Device, LED_Devices[Device])
              SDK.set_led_colors_flush_buffer()
`

**Comment by intrueder** [comment]
There are two issues: incorrect dictionary used in `for` loop and indentation issue.

```python
from cuesdk import CueSdk

SDK = CueSdk()
SDK.connect()
Device_Count = SDK.get_device_count()
LED_Devices = dict()
for Device in range(Device_Count):

    LED_Devices[Device] = SDK.get_led_positions_by_device_index(Device)

    for LED in LED_Devices[Device].keys(): # added  [Device]
        LED_Devices[Device][LED] = (255, 255, 255)

        print(type(Device))
        print(type(LED_Devices[Device]))
    SDK.set_led_colors_buffer_by_device_index(Device, LED_Devices[Device]) # moved this line to outer loop
    SDK.set_led_colors_flush_buffer()
```
