### ISSUE TITLE
Event Callback Not Working

### ISSUE THREAD

**Issue by stratoscstr** [CorsairOfficial/cue-sdk-python#14]
I ran the example that you gave for events after doing the proper setup (correct python version, etc). The event callback was not ever triggered through keypresses or connecting a corsair device.

I ran the color pulse example and that worked fine, except for that I couldn't press +/- to change the speed either.

I checked for errors during the subscribe_for_events() function, but it reported back as a success.

I enabled Software and game integration as well for both devices, and when I run sdk.get_devices() it returns both of my connected Corsair devices.

Hope this info helps! Thank you!

**Comment by intrueder** [comment]
Output from example, when `K100 RGB` is connected and `G1` is pressed/released:
```
Working... Press any G/M key or connect/disconnect Corsair device to see events in action

Press 'q' to close program...
Event: CorsairEventId.KeyEvent
 Device id: 50bcd1a5ebfeabc75e4a40f4427cfd85
    Key id: CorsairKeyId.Kb_G1
 Key state: pressed
Event: CorsairEventId.KeyEvent
 Device id: 50bcd1a5ebfeabc75e4a40f4427cfd85
    Key id: CorsairKeyId.Kb_G1
 Key state: released
```

What keyboard is connected to your system and what keys do you press?

**Comment by stratoscstr** [comment]
I have a K70 Mk. 2 keyboard. I tried pressing a bunch of different keys. Does this not pass through all key events? Is it only macro keys?

Maybe I misunderstood the example.

**Comment by intrueder** [comment]
Yes, iCUE reports pressed/released events for macro keys only (G keys on keyboard and M keys on mouse)
