### ISSUE TITLE
AIO Support

### ISSUE THREAD

**Issue by ptbrown35** [CorsairOfficial/cue-sdk-python#3]
Are there any plans on supporting AIO lighting and pump control?

**Comment by Legion2** [comment]
Here is a [list of supported devices](https://corsairofficial.github.io/cue-sdk/#supported-devices) which AIO are you missing?

**Comment by ptbrown35** [comment]
I'm running an H115i (non-pro, non-platinum) which looks like it's not supported. At any rate, it doesn't show up when I run `sdk.get_devices()`.

**Comment by Legion2** [comment]
Do you have any other corsair devices that are in the list, else check that the sdk is enabled in iCUE?

**Comment by ptbrown35** [comment]
I also have the Lighting Node Pro which works just fine.

**Comment by intrueder** [comment]
H115i does not support real-time lighting, only hardware playback. Hence, there is no reason to support it in this SDK.
