### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by thops** [CorsairOfficial/cue-sdk-python#6]
Hi,
I am wondering if there is a plan to allow this python package to install on MacOS.
From what I can tell, the biggest hurdle is distribution of the actual SDK files for MacOS since they need to be packaged in such a way that symbolic links are present (for code signing), which pip apparently does not support.

If this is the only issue, can we just include instructions for installing the SDK and add MacOS support to this package?

**Comment by intrueder** [comment]
Hi @thops 

Actually, nothing stops you from _installing_ this package on MacOS.
But as it only contains the Windows CUESDK binaries, you need to download MacOS version on your own (https://forum.corsair.com/v3/showthread.php?t=198443)

Extract `CUESDK.framework` to some location and use its **full path** in `CueSdk` constructor.

```py
sdk = CueSdk('/FULL_PATH/CUESDK.framework/CUESDK')
sdk.connect()
```
